### ISSUE TITLE
Convert orxStructs to Eu Constants?

### ISSUE THREAD

**Issue by gAndy50** [gAndy50/EuOrx#3]
There are a handful of structs in Orx that may benefit from being converted to Euphoria constant types.

**Comment by ghaberek** [comment]
Keep an eye out for opaque use of structs. Any struct whose members don't need to be referenced directly can probably be skipped. And those that do might benefit from writing accessor functions, e.g. `orx[StructName]_Get[MemberName]( atom ptr )`

**Comment by gAndy50** [comment]
Noted.

**Comment by gAndy50** [comment]
Converted structs added.
