### ISSUE TITLE
C enumerators are signed int, not unsigned

### ISSUE THREAD

**Issue by ghaberek** [gAndy50/EuOrx#5]
I noticed that you've wrapped any function call that uses enums (`orxMODULE_ID`, `orxSTATUS`, etc.) as `C_UINT` but C [enums](https://en.cppreference.com/w/c/language/enum) are signed integers, so we need to use `C_INT` instead. Not sure if this will affect anything as long as the type sizes match. I'm working on separating all the functions to their respective include files so I can update them as I go.

**Comment by gAndy50** [comment]
Thanks, I will keep this in mind for future wrapping.

**Comment by gAndy50** [comment]
I've been converting the unsigned to signed, so this is solved as well.
