### ISSUE TITLE
Add notes about building Win32 library

### ISSUE THREAD

**Issue by ghaberek** [gAndy50/EuOrx#7]
I moved orx.dll to the [win32](https://github.com/gAndy50/EuOrx/tree/main/win32) directory. Can you add new README.md to that directory with some details on the steps you took to build that particular library? We can add a note to the main README.md that any other binaries can be downloaded directly from Orx. We should also move any binaries we create to [Releases](https://github.com/gAndy50/EuOrx/releases) and keep them out of the source tree.

**Comment by gAndy50** [comment]
Noted Greg. I'll make a new README for that directory. It was fairly to simple build Orx using the CDECL calling convention.

**Comment by gAndy50** [comment]
I've added a README on how I compiled/built Orx. I can add more info if it is needed. I'm going to close this as this issue has been solved.
